name: mspypeline
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.17.4
  - pandas=0.25.3
  - scipy=1.3.1
  - rpy2=2.9.4
  - tzlocal=2.0.0
  - ruamel_yaml=0.15.46
  - matplotlib=3.1.1
  - matplotlib-venn=0.11.5
  - adjusttext=0.7.3.1
  - scikit-learn=0.22.1
  - plotly=4.6.0
  - sphinx=3.0.4
  - sphinx-autoapi=1.4.0
  - sphinx_rtd_theme=0.4.3
prefix: C:\Users\admvlasov\Anaconda3\envs\mspypeline

