# ##### MAIN SETTINGS ########
# settings that affect data processing

selected_reader: mqreader  # which file reader should be used
selected_normalizer: None  # which normalizer should be used

has_techrep: true  # does the file have technical replicates (can be "true" or "false")

use_protein_id: false   # should the protein id be used (can be "true" or "false"), or TODO

equal_variance: false   # should equal variance be assumed for the t-test? (can be "true" or "false")

pathways: []       # list of pathways which should be analyzed
go_terms: []       # list of go_terms which should be analyzed

mqreader: {}

# ###### PLOT CREATION SETTINGS #######
# settings that determine which results will be created
plot_normalization_overview_all_normalizers_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_heatmap_overview_all_normalizers_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_detection_counts_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_detected_proteins_per_replicate_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_venn_results_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_venn_groups_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_pca_overview_settings:
  create_plot: false
  dfs_to_use: []
  levels: []
  no_missing_values: true      # should missing values be neglected? (can be "true" or "false")

plot_intensity_histograms_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_relative_std_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_scatter_replicates_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_experiment_comparison_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_rank_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_pathway_analysis_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_go_analysis_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_r_volcano_settings:
  create_plot: false
  dfs_to_use: []
  levels: []
  adj_pval: false # should the adjusted p-val be used? (can be "true" or "false")

