# ##### MAIN SETTINGS ########
# settings that effect which results will be created

selected_reader: mqreader
selected_normalizer: None

pathways: []
# list of pathways which should be analyzed

go_terms: []
# list of go_terms which should be analyzed

has_techrep: false
# does the file have technical replicates
# can be "true" or "false"

# ###### PLOT CREATION SETTINGS #######

plot_normalization_overview_all_normalizers_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_heatmap_overview_all_normalizers_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_detection_counts_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_number_of_detected_proteins_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_intensity_histograms_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_relative_std_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_rank_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_pathway_analysis_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_scatter_replicates_settings:
  create_plot: true
  dfs_to_use:
    - raw_normalized_log2
  levels: []

plot_experiment_comparison_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_go_analysis_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_venn_results_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_r_volcano_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_venn_groups_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_pca_overview_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

use_protein_id: false
# should the protein id be used, or TODO
# can be "true" or "false"

equal_variance: false
plot_detected_proteins_per_replicate_settings:
  create_plot: false
  dfs_to_use: []
  levels: []
has_groups: false
# should equal variance be assumed for the t-test?
# can be "true" or "false"
